src/objects/CodeReviewHistory__b.object
<CustomObject>
    <fields>
        <fullName>CanBeMerged__c</fullName>
        <label>Can Be Merged</label>
        <length>80</length>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>CodeReviewDate__c</fullName>
        <label>Code Review Date</label>
        <required>true</required>
        <type>DateTime</type>
    </fields>
    <fields>
        <fullName>Comments__c</fullName>
        <label>Comments</label>
        <length>255</length>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>Employee__c</fullName>
        <label>Employee</label>
        <referenceTo>Employee__c</referenceTo>
        <relationshipName>CodeReviewsHistory</relationshipName>
        <required>true</required>
        <type>Lookup</type>
    </fields>
    <fields>
        <fullName>EstimatedHours__c</fullName>
        <label>Estimated Hours</label>
        <precision>18</precision>
        <required>true</required>
        <scale>0</scale>
        <type>Number</type>
    </fields>
    <fields>
        <fullName>RealHours__c</fullName>
        <label>Real Hours</label>
        <precision>18</precision>
        <required>true</required>
        <scale>0</scale>
        <type>Number</type>
    </fields>
    <fields>
        <fullName>Score__c</fullName>
        <label>Score</label>
        <precision>1</precision>
        <scale>0</scale>
        <type>Number</type>
    </fields>
    <fields>
        <fullName>Story__c</fullName>
        <label>Story__c</label>
        <referenceTo>Story__c</referenceTo>
        <relationshipName>CodeReviewsHistory</relationshipName>
        <required>true</required>
        <type>Lookup</type>
    </fields>
    <label>Code Review History</label>
    <pluralLabel>Code Reviews History</pluralLabel>
</CustomObject>

src/objects/Employee__c.object
<CustomObject>
    <label>Employee</label>
    <nameField>
        <displayFormat>E-{0000}</displayFormat>
        <label>Name</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Employees</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

src/objects/Story__c.object
<CustomObject>
    <fields>
        <fullName>EstimatedHours__c</fullName>
        <label>Estimated Hours</label>
        <precision>18</precision>
        <scale>0</scale>
        <type>Number</type>
    </fields>
    <fields>
        <fullName>RealHours__c</fullName>
        <label>RealHours</label>
        <precision>18</precision>
        <scale>0</scale>
        <type>Number</type>
    </fields>
    <label>Story</label>
    <nameField>
        <displayFormat>S-{0000}</displayFormat>
        <label>Name</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Stories</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

src/classes/CodeReviewHistoryController.cls
public with sharing class CodeReviewHistoryController {

	@AuraEnabled
	public static List<CodeReviewHistory__b> getCodeReviewsHistory() {
		return [SELECT CanBeMerged__c, CodeReviewDate__c, Comments__c, Employee__r.Name, 
		EstimatedHours__c, RealHours__c, Score__c, Story__c FROM CodeReviewHistory__b];
	}

	@AuraEnabled
	public static void addCodeReviewHistory(CodeReviewHistory__b codeReviewHistory) {
		Database.insertImmediate(new List<sObject>{codeReviewHistory});
	}
}